spring:
  application:
    name: moduleusers
  datasource:
    url: jdbc:h2:file:./db/moduleuser
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    properties:
      hibernate:
        use_sql_comments: false
        format_sql: false
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
server:
  port: 8081
