
INSERT INTO roles (name) SELECT 'GERENTE' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'GERENTE');
INSERT INTO roles (name) SELECT 'LOGISTICA' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'LOGISTICA');
INSERT INTO roles (name) SELECT 'VENDEDOR' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'VENDEDOR');
INSERT INTO roles (name) SELECT 'USUARIO' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'USUARIO');